services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
