services:
  app:
    container_name: ${PROJECT_NAME}
    networks:
      - server-internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  server-internal-net:
    external: true
